services:
  # Eureka Discovery Server
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - redis
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  # Organization Service
  organization-service:
    build:
      context: ./organization-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_REDIS_HOST=redis
    networks:
      - spring-cloud

  # Event Service
  event-service:
    build:
      context: ./event-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - spring-cloud

  # News Service (GraphQL)
  news-service:
    build:
      context: ./news-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - spring-cloud

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # messaging port
      - "15672:15672"   # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - spring-cloud

  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - spring-cloud

networks:
  spring-cloud:
