server:
  port: 8080

spring:
  application:
    name: api-gateway
  banner:
    location: classpath:banner.txt
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 3
            redis-rate-limiter.burstCapacity: 3
            key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=1
        - id: news-service
          uri: lb://news-service
          predicates:
            - Path=/news/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
